import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="bg-slate-800 text-gray-50">{children}</body>
      </AuthProvider>
    </html>
  );
}
