import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="bg-slate-800 text-gray-50">{children}</body>
      </html>
    </AuthProvider>
  );
}
